### ISSUE TITLE
Regarding vendor folder

### ISSUE THREAD

**Issue by fortm** [marcusolsson/pathfinder#1]
I find many more dependencies inside vendor folder than being used in go files in imports.
After copying the repository, I removed vendor folder and then did these -

```
glide create
glide install

```

This creates vendor folder with only those dependencies that are needed by code in import statements.  But go install then gives error as below - 

```
apples-MacBook-Pro:pathfinder apple$ go install
# github.com/marcusolsson/pathfinder
./main.go:43: cannot use encodeError (type func("net/http".ResponseWriter, error)) as type "github.com/marcusolsson/pathfinder/vendor/github.com/go-kit/kit/transport/http".ErrorEncoder in argument to "github.com/marcusolsson/pathfinder/vendor/github.com/go-kit/kit/transport/http".ServerErrorEncoder
./main.go:48: cannot use decodeShortestPathRequest (type func(*"net/http".Request) (interface {}, error)) as type "github.com/marcusolsson/pathfinder/vendor/github.com/go-kit/kit/transport/http".DecodeRequestFunc in argument to "github.com/marcusolsson/pathfinder/vendor/github.com/go-kit/kit/transport/http".NewServer
./main.go:48: cannot use encodeResponse (type func("net/http".ResponseWriter, interface {}) error) as type "github.com/marcusolsson/pathfinder/vendor/github.com/go-kit/kit/transport/http".EncodeResponseFunc in argument to "github.com/marcusolsson/pathfinder/vendor/github.com/go-kit/kit/transport/http".NewServer
```

Am I doing vendoring incorrectly here with Go 1.7 ?

**Comment by marcusolsson** [comment]
I'm currently using `gvt` for vendoring which recursively fetches dependencies. `go-kit` pulls in quite a few dependencies, many of which are not being used. 

By removing the vendor directory and creating a fresh one you're pulling in the latest versions of the dependencies. It looks like changes have been made to gokit and that pathfinder should adopt the new changes. 

EDIT: If you want to make the fixes and update the dependencies, I'd be happy to accept it as a pull request :)

**Comment by marcusolsson** [comment]
I'm closing this but feel free to add to it, should I have missed something.
